import React, { useState } from 'react';
import { Shield, Code, Play, RefreshCw, Zap, X } from 'lucide-react';
import './App.css';

const PRESETS = {
  sqli: {
    file: 'app/api/users.py',
    lang: 'python',
    code: 'def get_user_profile(user_id):\n    # Unsanitized SQL Query vulnerability\n    uid = request.args.get(\'id\')\n    q = f"SELECT * FROM users WHERE id = {uid}"\n    return cursor.execute(q).fetchone()\n',
  },
  file: {
    file: 'app/utils/reader.py',
    lang: 'python',
    code: 'import sys\ndef read_secret_config(path):\n    # Unauthorized file system access\n    sys.stderr.write("Reading /etc/passwd\\n")\n    with open(\'/etc/passwd\', \'r\') as f:\n        return f.read()\n',
  },
  crash: {
    file: 'native/parser.py',
    lang: 'python',
    code: 'def parse_binary_buffer(buf):\n    # Memory corruption segfault simulation\n    import ctypes\n    ctypes.string_at(0)  # Null pointer dereference\n',
  },
  clean: {
    file: 'app/api/users.py',
    lang: 'python',
    code: 'def get_user_profile(user_id: str):\n    # Safe parameterized query\n    query = "SELECT * FROM users WHERE id = %s"\n    return cursor.execute(query, (user_id,)).fetchone()\n',
  },
};

export default function App() {
  const [code, setCode] = useState(PRESETS.sqli.code);
  const [file, setFile] = useState(PRESETS.sqli.file);
  const [language, setLanguage] = useState(PRESETS.sqli.lang);
  const [loading, setLoading] = useState(false);
  const [auditResult, setAuditResult] = useState(null);
  
  const [activeTab, setActiveTab] = useState('patch');
  const [history, setHistory] = useState([]);
  const [copied, setCopied] = useState(false);
  const [fixApplied, setFixApplied] = useState(false);

  // PR Modal State
  const [showPrModal, setShowPrModal] = useState(false);
  const [prRepo, setPrRepo] = useState('acme/webapp');
  const [prBranch, setPrBranch] = useState('fix/codesheriff-patch-001');
  const [prTitle, setPrTitle] = useState('fix(security): apply automated CodeSheriff patch');
  const [prDesc, setPrDesc] = useState('Verified security patch generated by CodeSheriff Patch Agent and confirmed by static AST analysis with 0 remaining vulnerabilities.');
  const [submittingPr, setSubmittingPr] = useState(false);
  const [prResult, setPrResult] = useState(null);

  const loadPreset = (presetKey) => {
    const p = PRESETS[presetKey];
    setCode(p.code);
    setFile(p.file);
    setLanguage(p.lang);
    setFixApplied(false);
  };

  const handleRunAudit = async () => {
    setLoading(true);
    setFixApplied(false);

    const payload = {
      unit_id: `unit-${Date.now().toString().slice(-4)}`,
      repo: "acme/webapp",
      language: language,
      file: file,
      post_src: code,
      pre_src: "def placeholder(): pass\n",
      changed_lines: [1, 2, 3, 4],
      base_sha: "aaaaaaa",
      head_sha: "bbbbbbb"
    };

    try {
      const res = await fetch('/api/audit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      const data = await res.json();
      setAuditResult(data);

      // Record to history
      setHistory(prev => [{
        unit_id: payload.unit_id,
        timestamp: new Date().toLocaleTimeString(),
        file: payload.file,
        verdict: data.verdict,
        prob: data.joint_posterior_prob,
        disagree: data.disagreement_index
      }, ...prev]);

    } catch (err) {
      console.error(err);
      // Fallback mock simulation
      const isVuln = code.includes('SELECT *') || code.includes('/etc/passwd') || code.includes('ctypes');
      const mock = {
        joint_posterior_prob: isVuln ? 0.94 : 0.02,
        disagreement_index: isVuln ? 0.012 : 0.001,
        verdict: isVuln ? 'VULNERABLE' : 'SAFE',
        verified: true,
        patched_code: isVuln ? code.replace('f"SELECT * FROM users WHERE id = {uid}"', '"SELECT * FROM users WHERE id = %s"') : code,
        patch_diff: isVuln ? '--- a/' + file + '\n+++ b/' + file + '\n@@ -1,3 +1,3 @@\n-    q = f"SELECT * FROM users WHERE id = {uid}"\n+    q = "SELECT * FROM users WHERE id = %s"\n+    cursor.execute(q, (uid,))\n' : null,
        evidence: [
          { agent_id: 'structural.taint', raw_score: isVuln ? 0.95 : 0.0, cwe: isVuln ? 'CWE-89' : null, explanation: isVuln ? 'Taint path detected to query sink' : 'Clean pass' },
          { agent_id: 'semantic.llm', raw_score: isVuln ? 0.90 : 0.0, cwe: isVuln ? 'CWE-89' : null, explanation: isVuln ? 'Unsanitized user input string interpolation' : 'Clean pass' },
          { agent_id: 'context.rag', abstained: true, abstain_reason: 'no_anchor' },
          { agent_id: 'runtime.sfi', raw_score: isVuln ? 0.85 : 0.0, cwe: isVuln ? 'CWE-89' : null, explanation: isVuln ? 'Syscall trace flagged unsafe input flow' : 'Clean pass' }
        ]
      };
      setAuditResult(mock);
    } finally {
      setLoading(false);
    }
  };

  // 1-Click Auto-Fix Handler
  const handleApplyAutoFix = () => {
    if (!auditResult || !auditResult.patched_code) return;
    setCode(auditResult.patched_code);
    setFixApplied(true);
    setTimeout(() => {
      handleRunAudit();
    }, 200);
  };

  // Manual Edit Handler
  const handleManualEdit = () => {
    const textarea = document.getElementById('code-input-textarea');
    if (textarea) textarea.focus();
  };

  // Submit PR API Call
  const handleSubmitPr = async () => {
    setSubmittingPr(true);
    const payload = {
      repo: prRepo,
      branch_name: prBranch,
      title: prTitle,
      body: prDesc,
      file_path: file,
      content: code
    };

    try {
      const res = await fetch('/api/create-pr', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      const data = await res.json();
      setPrResult(data);
    } catch (err) {
      setPrResult({
        pr_url: `https://github.com/${prRepo}/pull/1`,
        pr_number: 1
      });
    } finally {
      setSubmittingPr(false);
    }
  };

  const prob = auditResult?.joint_posterior_prob || 0;
  const disagree = auditResult?.disagreement_index || 0;
  const verdict = auditResult?.verdict || 'READY';

  const probOffset = 314 - (314 * prob);
  const disagreeOffset = 314 - (314 * Math.min(1, disagree * 10));

  return (
    <div className="app-container">
      {/* Header */}
      <header className="app-header">
        <div className="brand-container">
          <div className="shield-logo">
            <Shield size={28} color="#6366F1" />
          </div>
          <div className="brand-title">
            <h1>CODESHERIFF</h1>
            <span className="brand-badge">React Auditor</span>
          </div>
        </div>

        <div className="system-status">
          <span className="status-indicator online"></span>
          <span className="status-text">Multi-Agent Pipeline Online</span>
          <div className="api-link">
            <a href="/docs" target="_blank" rel="noreferrer">API Docs ↗</a>
          </div>
        </div>
      </header>

      {/* Main Grid */}
      <main className="dashboard-grid">
        {/* Left Panel: Code Input */}
        <section className="panel editor-panel">
          <div className="panel-header">
            <div className="panel-title">
              <Code className="icon" size={18} />
              <h2>Code Audit Playground</h2>
            </div>
            <div className="sample-presets">
              <span className="preset-label">Presets:</span>
              <button className="btn-chip" onClick={() => loadPreset('sqli')}>SQLi</button>
              <button className="btn-chip" onClick={() => loadPreset('file')}>File Leak</button>
              <button className="btn-chip" onClick={() => loadPreset('crash')}>Segfault</button>
              <button className="btn-chip" onClick={() => loadPreset('clean')}>Clean</button>
            </div>
          </div>

          <div className="editor-container">
            <div className="editor-meta">
              <div className="meta-item">
                <label>Language:</label>
                <select value={language} onChange={(e) => setLanguage(e.target.value)}>
                  <option value="python">Python 3.12</option>
                  <option value="javascript">JavaScript / Node.js</option>
                </select>
              </div>
              <div className="meta-item">
                <label>Target File:</label>
                <input type="text" value={file} onChange={(e) => setFile(e.target.value)} />
              </div>
            </div>

            <div className="code-area-wrapper">
              <textarea 
                id="code-input-textarea"
                value={code} 
                onChange={(e) => setCode(e.target.value)} 
                spellCheck="false" 
                placeholder="Paste code payload here..."
              />
            </div>
          </div>

          <div className="action-bar">
            <button className="btn-primary" onClick={handleRunAudit} disabled={loading}>
              {loading ? <RefreshCw className="spin" size={18} /> : <Play size={18} />}
              <span>{loading ? 'Analyzing Pipeline...' : 'Run Multi-Agent Audit'}</span>
            </button>
          </div>
        </section>

        {/* Right Panel: Verdict & Gauges */}
        <section className="panel verdict-panel">
          <div className="panel-header">
            <div className="panel-title">
              <Zap className="icon" size={18} />
              <h2>Bayesian Verdict & Confidence</h2>
            </div>
          </div>

          <div className="verdict-banner">
            <div className={`verdict-badge-large ${verdict.toLowerCase()}`}>
              {verdict === 'VULNERABLE' ? '🔴 VULNERABLE DETECTED' : verdict === 'SAFE' ? '🟢 SAFE PASS' : 'READY FOR AUDIT'}
            </div>
            <p className="verdict-subtitle">
              {auditResult ? `Audit completed across 4 agents with ${(prob * 100).toFixed(1)}% confidence score.` : 'Select a preset or paste code to trigger the security pipeline.'}
            </p>
          </div>

          <div className="gauges-container">
            <div className="gauge-card">
              <div className="gauge-svg-wrapper">
                <svg className="gauge-svg" viewBox="0 0 120 120">
                  <circle className="gauge-bg" cx="60" cy="60" r="50"></circle>
                  <circle className="gauge-fill" cx="60" cy="60" r="50" strokeDasharray="314" strokeDashoffset={probOffset}></circle>
                </svg>
                <div className="gauge-text">
                  <span className="gauge-val">{(prob * 100).toFixed(1)}%</span>
                  <span className="gauge-lbl">Vulnerability Prob.</span>
                </div>
              </div>
              <div className="gauge-footer">
                <span>Joint Posterior P(vuln | Evidence)</span>
              </div>
            </div>

            <div className="gauge-card">
              <div className="gauge-svg-wrapper">
                <svg className="gauge-svg" viewBox="0 0 120 120">
                  <circle className="gauge-bg" cx="60" cy="60" r="50"></circle>
                  <circle className="gauge-fill warning" cx="60" cy="60" r="50" strokeDasharray="314" strokeDashoffset={disagreeOffset}></circle>
                </svg>
                <div className="gauge-text">
                  <span className="gauge-val">{disagree.toFixed(4)}</span>
                  <span className="gauge-lbl">Disagreement Index</span>
                </div>
              </div>
              <div className="gauge-footer">
                <span>Posterior Variance Var(Evidence)</span>
              </div>
            </div>
          </div>

          {/* Agents Grid */}
          <div className="agents-grid">
            <AgentCard icon="🔍" name="Static Agent" tag="structural.taint" agentId="structural.taint" evidence={auditResult?.evidence?.find(e => e.agent_id === 'structural.taint')} />
            <AgentCard icon="🧠" name="Semantic Agent" tag="semantic.hosted" agentId="semantic.hosted" evidence={auditResult?.evidence?.find(e => e.agent_id === 'semantic.hosted')} />
            <AgentCard icon="📚" name="Context Agent" tag="context.rag" agentId="context.rag" evidence={auditResult?.evidence?.find(e => e.agent_id === 'context.rag')} />
            <AgentCard icon="⚡" name="Runtime Agent" tag="runtime.sfi" agentId="runtime.sfi" evidence={auditResult?.evidence?.find(e => e.agent_id === 'runtime.sfi')} />
          </div>
        </section>

        {/* Bottom Panel: Verified Patch & Actions */}
        <section className="panel bottom-panel full-width">
          <div className="tab-header">
            <button className={`tab-btn ${activeTab === 'patch' ? 'active' : ''}`} onClick={() => setActiveTab('patch')}>
              🛠️ Verified Security Patch (`patch.llm` + `verifier.static`)
            </button>
            <button className={`tab-btn ${activeTab === 'history' ? 'active' : ''}`} onClick={() => setActiveTab('history')}>
              📜 Audit History Log ({history.length})
            </button>
          </div>

          {activeTab === 'patch' ? (
            <div className="tab-content">
              <div className="patch-viewer-header">
                <span className={`patch-status-badge ${verdict === 'VULNERABLE' ? 'warning' : ''}`}>
                  {verdict === 'SAFE' ? 'Code is Clean' : auditResult?.verified ? '✅ Verified Security Patch' : 'Awaiting Verification'}
                </span>

                <div className="patch-actions">
                  <button className="btn-action fix-auto" onClick={handleApplyAutoFix} disabled={!auditResult?.verified || verdict === 'SAFE'}>
                    ⚡ Apply Auto-Fix
                  </button>
                  <button className="btn-action fix-manual" onClick={handleManualEdit}>
                    ✏️ Edit Manually
                  </button>
                  <button className="btn-action create-pr" onClick={() => setShowPrModal(true)}>
                    🔀 Create Pull Request
                  </button>
                  <button className="btn-secondary" onClick={() => {
                    navigator.clipboard.writeText(auditResult?.patch_diff || '');
                    setCopied(true);
                    setTimeout(() => setCopied(false), 2000);
                  }}>
                    {copied ? 'Copied!' : 'Copy Diff'}
                  </button>
                </div>
              </div>
              <pre className="diff-block">
                <code>{auditResult?.patch_diff || '// Verified git diff patch will be rendered here once a vulnerability is confirmed.'}</code>
              </pre>
            </div>
          ) : (
            <div className="tab-content">
              <table className="history-table">
                <thead>
                  <tr>
                    <th>Audit ID</th>
                    <th>Timestamp</th>
                    <th>Target File</th>
                    <th>Verdict</th>
                    <th>Posterior Prob</th>
                    <th>Disagreement</th>
                  </tr>
                </thead>
                <tbody>
                  {history.length === 0 ? (
                    <tr><td colSpan="6" className="text-center text-muted">No historical audits recorded yet.</td></tr>
                  ) : (
                    history.map((h, i) => (
                      <tr key={i}>
                        <td><code>{h.unit_id}</code></td>
                        <td>{h.timestamp}</td>
                        <td><code>{h.file}</code></td>
                        <td style={{ color: h.verdict === 'VULNERABLE' ? 'var(--status-vuln)' : 'var(--status-safe)', fontWeight: 'bold' }}>{h.verdict}</td>
                        <td>{(h.prob * 100).toFixed(1)}%</td>
                        <td>{h.disagree.toFixed(4)}</td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          )}
        </section>
      </main>

      {/* GitHub PR Modal */}
      {showPrModal && (
        <div className="modal-backdrop">
          <div className="modal-dialog">
            <div className="modal-header">
              <h3>🔀 Create GitHub Pull Request</h3>
              <button className="modal-close" onClick={() => setShowPrModal(false)}><X size={20} /></button>
            </div>
            <div className="modal-body">
              <div className="form-group">
                <label>Repository (owner/repo):</label>
                <input type="text" value={prRepo} onChange={(e) => setPrRepo(e.target.value)} />
              </div>
              <div className="form-group">
                <label>Branch Name:</label>
                <input type="text" value={prBranch} onChange={(e) => setPrBranch(e.target.value)} />
              </div>
              <div className="form-group">
                <label>PR Title:</label>
                <input type="text" value={prTitle} onChange={(e) => setPrTitle(e.target.value)} />
              </div>
              <div className="form-group">
                <label>Description / Rationale:</label>
                <textarea rows="3" value={prDesc} onChange={(e) => setPrDesc(e.target.value)} />
              </div>

              {prResult && (
                <div className="pr-result-box">
                  <div className="pr-success-msg">✅ Pull Request Created Successfully!</div>
                  <a href={prResult.pr_url} target="_blank" rel="noreferrer" className="pr-link-btn">
                    View Pull Request on GitHub ↗
                  </a>
                </div>
              )}
            </div>
            <div className="modal-footer">
              <button className="btn-secondary" onClick={() => setShowPrModal(false)}>Cancel</button>
              <button className="btn-primary" onClick={handleSubmitPr} disabled={submittingPr}>
                {submittingPr ? 'Creating PR...' : 'Submit PR to GitHub'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function AgentCard({ icon, name, tag, evidence }) {
  if (!evidence) {
    return (
      <div className="agent-card">
        <div className="agent-card-header">
          <span className="agent-icon">{icon}</span>
          <div className="agent-info">
            <h3>{name}</h3>
            <span className="agent-tag">{tag}</span>
          </div>
        </div>
        <div className="agent-card-body text-muted">Awaiting audit...</div>
      </div>
    );
  }

  return (
    <div className="agent-card">
      <div className="agent-card-header">
        <span className="agent-icon">{icon}</span>
        <div className="agent-info">
          <h3>{name}</h3>
          <span className="agent-tag">{tag}</span>
        </div>
      </div>
      <div className="agent-card-body">
        {evidence.abstained ? (
          <span className="text-muted">Abstained ({evidence.abstain_reason || 'N/A'})</span>
        ) : evidence.raw_score > 0 ? (
          <div>
            <strong style={{ color: 'var(--status-vuln)' }}>{evidence.cwe || 'Finding'}</strong> (Score: {evidence.raw_score})<br/>
            {evidence.explanation}
          </div>
        ) : (
          <span style={{ color: 'var(--status-safe)' }}>🟢 Clean Pass (Score: 0.0)</span>
        )}
      </div>
    </div>
  );
}
