"""CodeSheriff persistence.

Imported by `apps/worker` (writes) and `apps/api` (reads). Never by an agent, and never by
`codesheriff_engine` — see D-025 and the `lint-imports` contracts in the root `pyproject.toml`.
"""

from codesheriff_storage.audits import (
    audit_for_delivery,
    calibration_run_for,
    claim_audit,
    fail_audit,
    finish_audit,
    is_superseded,
    latest_comment_id,
    open_audit,
    supersede_open_audits,
)
from codesheriff_storage.config import DEFAULT_DATABASE_URL, StorageConfig
from codesheriff_storage.identity import (
    create_session,
    delete_installation,
    delete_repositories,
    ensure_installation,
    ensure_repository,
    hash_session_token,
    list_repositories,
    purge_expired_sessions,
    repository_by_id,
    revoke_session,
    session_for_token,
    set_analysis_enabled,
    touch_session,
    upsert_installation,
    upsert_repository,
    upsert_user,
)
from codesheriff_storage.mapping import (
    is_wellformed_finding_key,
    persistable_findings,
    sha256_text,
    to_change_unit_row,
    to_evidence_row,
    to_finding,
)
from codesheriff_storage.models import (
    EMBEDDING_DIM,
    FINDING_KEY_PATTERN,
    OPEN_AUDIT_STATUSES,
    Audit,
    AuditStatus,
    Base,
    CalibrationRun,
    ChangeUnitRow,
    EvidenceKindDB,
    EvidenceRow,
    Finding,
    Installation,
    PrecedentChunk,
    PRPrecedent,
    Repository,
    Session,
    User,
)
from codesheriff_storage.precedents import PrecedentMatch, build_chunk, search_precedents
from codesheriff_storage.session import build_engine, build_session_factory, session_scope

__all__ = [
    "DEFAULT_DATABASE_URL",
    "EMBEDDING_DIM",
    "FINDING_KEY_PATTERN",
    "OPEN_AUDIT_STATUSES",
    "Audit",
    "AuditStatus",
    "Base",
    "CalibrationRun",
    "ChangeUnitRow",
    "EvidenceKindDB",
    "EvidenceRow",
    "Finding",
    "Installation",
    "PRPrecedent",
    "PrecedentChunk",
    "PrecedentMatch",
    "Repository",
    "Session",
    "StorageConfig",
    "User",
    "audit_for_delivery",
    "build_chunk",
    "build_engine",
    "build_session_factory",
    "calibration_run_for",
    "claim_audit",
    "create_session",
    "delete_installation",
    "delete_repositories",
    "ensure_installation",
    "ensure_repository",
    "fail_audit",
    "finish_audit",
    "hash_session_token",
    "is_superseded",
    "is_wellformed_finding_key",
    "latest_comment_id",
    "list_repositories",
    "open_audit",
    "persistable_findings",
    "purge_expired_sessions",
    "repository_by_id",
    "revoke_session",
    "search_precedents",
    "session_for_token",
    "session_scope",
    "set_analysis_enabled",
    "sha256_text",
    "supersede_open_audits",
    "to_change_unit_row",
    "to_evidence_row",
    "to_finding",
    "touch_session",
    "upsert_installation",
    "upsert_repository",
    "upsert_user",
]
